In [29]:
import pandas as pd
from sklearn.linear_model import LinearRegression, ElasticNet
import numpy as np
from sklearn.metrics import r2_score 
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import make_column_transformer 
from sklearn.compose import make_column_selector
import os
os.chdir(r"C:\Training\Kaggle\Competitions\Playground Competitions\UsedCarsPrices")

In [30]:
train = pd.read_csv("train.csv", index_col=0)
train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 188533 entries, 0 to 188532
Data columns (total 12 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   brand         188533 non-null  object
 1   model         188533 non-null  object
 2   model_year    188533 non-null  int64 
 3   milage        188533 non-null  int64 
 4   fuel_type     183450 non-null  object
 5   engine        188533 non-null  object
 6   transmission  188533 non-null  object
 7   ext_col       188533 non-null  object
 8   int_col       188533 non-null  object
 9   accident      186081 non-null  object
 10  clean_title   167114 non-null  object
 11  price         188533 non-null  int64 
dtypes: int64(3), object(9)
memory usage: 18.7+ MB


In [31]:
X_train = train.drop('price', axis=1)
y_train = train['price']
ohe = OneHotEncoder(handle_unknown='infrequent_if_exist',
      sparse_output=False,min_frequency=3000).set_output(transform='pandas')
ct_ohe = make_column_transformer(('passthrough', make_column_selector(dtype_exclude=object)  ),
                             (ohe, make_column_selector(dtype_include=object) ),
                            verbose_feature_names_out=False).set_output(transform='pandas')

In [32]:
X_test = pd.read_csv("test.csv", index_col=0)
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Index: 125690 entries, 188533 to 314222
Data columns (total 11 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   brand         125690 non-null  object
 1   model         125690 non-null  object
 2   model_year    125690 non-null  int64 
 3   milage        125690 non-null  int64 
 4   fuel_type     122307 non-null  object
 5   engine        125690 non-null  object
 6   transmission  125690 non-null  object
 7   ext_col       125690 non-null  object
 8   int_col       125690 non-null  object
 9   accident      124058 non-null  object
 10  clean_title   111451 non-null  object
dtypes: int64(2), object(9)
memory usage: 11.5+ MB


In [37]:
elastic = ElasticNet()
kfold = KFold(n_splits=5, shuffle=True, random_state=24)
pipe = Pipeline([('CT',ct_ohe),('EL',elastic)])
params = {'EL__alpha':np.linspace(0.001, 5, 3),'EL__l1_ratio':np.linspace(0.0001, 1, 3)}
gcv_el = GridSearchCV(pipe, param_grid=params, verbose=3, cv=kfold)
gcv_el.fit(X_train,y_train)

Fitting 5 folds for each of 9 candidates, totalling 45 fits


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.242e+14, tolerance: 9.377e+10
  model = cd_fast.enet_coordinate_descent(


[CV 1/5] END EL__alpha=0.001, EL__l1_ratio=0.0001;, score=0.093 total time=  26.2s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.100e+14, tolerance: 9.096e+10
  model = cd_fast.enet_coordinate_descent(


[CV 2/5] END EL__alpha=0.001, EL__l1_ratio=0.0001;, score=0.082 total time=  25.8s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.258e+14, tolerance: 9.415e+10
  model = cd_fast.enet_coordinate_descent(


[CV 3/5] END EL__alpha=0.001, EL__l1_ratio=0.0001;, score=0.092 total time=  25.9s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.445e+14, tolerance: 9.775e+10
  model = cd_fast.enet_coordinate_descent(


[CV 4/5] END EL__alpha=0.001, EL__l1_ratio=0.0001;, score=0.116 total time=  26.2s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.152e+14, tolerance: 9.187e+10
  model = cd_fast.enet_coordinate_descent(


[CV 5/5] END EL__alpha=0.001, EL__l1_ratio=0.0001;, score=0.090 total time=  26.9s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.206e+14, tolerance: 9.377e+10
  model = cd_fast.enet_coordinate_descent(


[CV 1/5] END EL__alpha=0.001, EL__l1_ratio=0.50005;, score=0.093 total time=  26.6s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.063e+14, tolerance: 9.096e+10
  model = cd_fast.enet_coordinate_descent(


[CV 2/5] END EL__alpha=0.001, EL__l1_ratio=0.50005;, score=0.082 total time=  27.2s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.223e+14, tolerance: 9.415e+10
  model = cd_fast.enet_coordinate_descent(


[CV 3/5] END EL__alpha=0.001, EL__l1_ratio=0.50005;, score=0.092 total time=  27.0s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.408e+14, tolerance: 9.775e+10
  model = cd_fast.enet_coordinate_descent(


[CV 4/5] END EL__alpha=0.001, EL__l1_ratio=0.50005;, score=0.116 total time=  26.5s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.120e+14, tolerance: 9.187e+10
  model = cd_fast.enet_coordinate_descent(


[CV 5/5] END EL__alpha=0.001, EL__l1_ratio=0.50005;, score=0.090 total time=  27.4s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.177e+14, tolerance: 9.377e+10
  model = cd_fast.enet_coordinate_descent(


[CV 1/5] END .EL__alpha=0.001, EL__l1_ratio=1.0;, score=0.093 total time=  29.1s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.137e+14, tolerance: 9.096e+10
  model = cd_fast.enet_coordinate_descent(


[CV 2/5] END .EL__alpha=0.001, EL__l1_ratio=1.0;, score=0.082 total time=  27.9s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.182e+14, tolerance: 9.415e+10
  model = cd_fast.enet_coordinate_descent(


[CV 3/5] END .EL__alpha=0.001, EL__l1_ratio=1.0;, score=0.092 total time=  27.9s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.354e+13, tolerance: 9.775e+10
  model = cd_fast.enet_coordinate_descent(


[CV 4/5] END .EL__alpha=0.001, EL__l1_ratio=1.0;, score=0.116 total time=  27.6s


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.156e+14, tolerance: 9.187e+10
  model = cd_fast.enet_coordinate_descent(


[CV 5/5] END .EL__alpha=0.001, EL__l1_ratio=1.0;, score=0.090 total time=  28.0s
[CV 1/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.0001;, score=0.085 total time=   2.5s
[CV 2/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.0001;, score=0.073 total time=   2.5s
[CV 3/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.0001;, score=0.082 total time=   2.6s
[CV 4/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.0001;, score=0.102 total time=   2.5s
[CV 5/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.0001;, score=0.083 total time=   2.6s
[CV 1/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.50005;, score=0.085 total time=   2.3s
[CV 2/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.50005;, score=0.074 total time=   2.3s
[CV 3/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.50005;, score=0.083 total time=   2.3s
[CV 4/5] END EL__alpha=2.5004999999999997, EL__l1_ratio=0.50005;, score=0.103 total time=   2.5s
[CV 5/5] END EL__alpha=2.5004999999999997, EL__l1_r

C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.299e+14, tolerance: 1.171e+11
  model = cd_fast.enet_coordinate_descent(


GridSearchCV(cv=KFold(n_splits=5, random_state=24, shuffle=True),
             estimator=Pipeline(steps=[('CT',
                                        ColumnTransformer(transformers=[('passthrough',
                                                                         'passthrough',
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x000002082E5EEC60>),
                                                                        ('onehotencoder',
                                                                         OneHotEncoder(handle_unknown='infrequent_if_exist',
                                                                                       min_frequency=3000,
                                                                                       sparse_output=False),
                                                                         <sklearn.compose._column_transformer.make_column_selector object at 0x000002082E5EE750>)],
                                                          verbose_feature_names_out=False)),
                                       ('EL', ElasticNet())]),
             param_grid={'EL__alpha': array([1.0000e-03, 2.5005e+00, 5.0000e+00]),
                         'EL__l1_ratio': array([1.0000e-04, 5.0005e-01, 1.0000e+00])},
             verbose=3)

In [38]:
print("Best Params:", gcv_el.best_params_)
print("Best Score:", gcv_el.best_score_)

Best Params: {'EL__alpha': 0.001, 'EL__l1_ratio': 0.0001}
Best Score: 0.09454190128755835


In [41]:
bm_el = gcv_el.best_estimator_ 
y_pred = bm_el.predict(X_test)

In [43]:
y_pred[y_pred<0]

array([-5089.73939043, -1827.34107503, -9896.01083734, ...,
       -7126.21756188, -7558.91950968, -4438.98255956])

In [45]:
y_pred[y_pred<150] = 150

In [47]:
np.quantile(y_pred,[0,0.25,0.5,0.75,1])

array([   150.        ,  27217.87552815,  46903.87406877,  62647.77927378,
       109233.12392077])

In [49]:
submit = pd.read_csv("sample_submission.csv")
submit['price'] = y_pred
submit.to_csv("ss_5_nov_2_el.csv", index=False)

## K-NN Regressor

In [54]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import MinMaxScaler, StandardScaler
scaler_mm = MinMaxScaler()
scaler_std = StandardScaler()
ohe = OneHotEncoder(handle_unknown='infrequent_if_exist',
      sparse_output=False,min_frequency=3000).set_output(transform='pandas')
ct_ohe = make_column_transformer(('passthrough', make_column_selector(dtype_exclude=object)  ),
                             (ohe, make_column_selector(dtype_include=object) ),
                            verbose_feature_names_out=False).set_output(transform='pandas')

In [62]:
knn = KNeighborsRegressor()
pipe = Pipeline([('CT',ct_ohe),('SCL',None),('KNN',knn)])
kfold = KFold(n_splits=5, random_state=24,  shuffle=True)
params = {'KNN__n_neighbors': np.arange(1,8), 'SCL':[scaler_mm, scaler_std, None]}

In [ ]:
gcv = GridSearchCV(pipe, param_grid=params,  scoring='r2', cv=kfold, verbose=3)
gcv.fit(X_train,y_train)

Fitting 5 folds for each of 21 candidates, totalling 105 fits
[CV 1/5] END KNN__n_neighbors=1, SCL=MinMaxScaler();, score=-0.809 total time=  11.8s
[CV 2/5] END KNN__n_neighbors=1, SCL=MinMaxScaler();, score=-0.535 total time=  11.5s
[CV 3/5] END KNN__n_neighbors=1, SCL=MinMaxScaler();, score=-0.811 total time=  11.9s
[CV 4/5] END KNN__n_neighbors=1, SCL=MinMaxScaler();, score=-0.858 total time=  12.0s
[CV 5/5] END KNN__n_neighbors=1, SCL=MinMaxScaler();, score=-0.651 total time=  11.9s
[CV 1/5] END KNN__n_neighbors=1, SCL=StandardScaler();, score=-0.720 total time=  12.7s
[CV 2/5] END KNN__n_neighbors=1, SCL=StandardScaler();, score=-0.522 total time=  12.0s
[CV 3/5] END KNN__n_neighbors=1, SCL=StandardScaler();, score=-0.901 total time=  12.3s
[CV 4/5] END KNN__n_neighbors=1, SCL=StandardScaler();, score=-0.876 total time=  12.4s
[CV 5/5] END KNN__n_neighbors=1, SCL=StandardScaler();, score=-0.668 total time=  12.6s
[CV 1/5] END .....KNN__n_neighbors=1, SCL=None;, score=-0.681 total 

In [41]:
bm_knn = gcv.best_estimator_ 
y_pred = bm_knn.predict(X_test)

In [43]:
y_pred[y_pred<0]

array([-5089.73939043, -1827.34107503, -9896.01083734, ...,
       -7126.21756188, -7558.91950968, -4438.98255956])

In [45]:
y_pred[y_pred<150] = 150

In [47]:
np.quantile(y_pred,[0,0.25,0.5,0.75,1])

array([   150.        ,  27217.87552815,  46903.87406877,  62647.77927378,
       109233.12392077])

In [49]:
submit = pd.read_csv("sample_submission.csv")
submit['price'] = y_pred
submit.to_csv("ss_5_nov_2_el.csv", index=False)