In [1]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import KFold, cross_val_score, GridSearchCV

In [3]:
iris = pd.read_csv("C:/Python/Datasets/iris.csv")
iris.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [8]:
lbl = LabelEncoder()
iris['Species'] = lbl.fit_transform(iris['Species'])

In [30]:
lbl.classes_

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [10]:
y = iris['Species']
X = iris.drop('Species', axis=1)

In [12]:
y.value_counts()

Species
0    50
1    50
2    50
Name: count, dtype: int64

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=24, test_size=0.3)

In [16]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)

In [18]:
print(confusion_matrix(y_test, y_pred))

[[15  0  0]
 [ 0 11  1]
 [ 0  0 18]]


In [20]:
accuracy_score(y_test, y_pred)

0.9777777777777777

In [22]:
y_test.shape

(45,)

Naive Rule / Baseline Model

In [36]:
y_pred = np.repeat(2,y_test.shape[0])
y_pred

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2])

In [38]:
y_test.value_counts()

Species
2    18
0    15
1    12
Name: count, dtype: int64

In [40]:
accuracy_score(y_test, y_pred)

0.4

Any ML Model score should be better than score of baseline model.
Here baseline(naive) model score = 0.4 & ML Model score = 0.97. 
Hence we can say that this ML Model can be a relevant model. 

### Defaulter Dataset

In [51]:
from sklearn.preprocessing import OneHotEncoder 
from sklearn.compose import make_column_transformer 
from sklearn.compose import make_column_selector

In [45]:
default = pd.read_csv("C:/Python/Datasets/Default.csv")
default.head(3)

default student      balance       income
0      No      No   729.526495  44361.62507
1      No     Yes   817.180407  12106.13470
2      No      No  1073.549164  31767.13895

In [47]:
default['default'].value_counts()

default
No     9667
Yes     333
Name: count, dtype: int64

In [49]:
X = default.drop('default', axis=1)
y = default['default']

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=24, test_size=0.3)
ohe = OneHotEncoder(sparse_output=False, drop='first').set_output(transform='pandas')
ct = make_column_transformer(('passthrough', make_column_selector(dtype_exclude=object)  ),
                             (ohe, make_column_selector(dtype_include=object) ),
                            verbose_feature_names_out=False).set_output(transform='pandas')
pipe = Pipeline([('CT', ct), ('LR', lr)])
pipe.fit(X_train, y_train)
y_pred = pipe.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.97


Naive Model

In [62]:
y_test.value_counts()

default
No     2901
Yes      99
Name: count, dtype: int64

In [67]:
y_pred_nv = np.repeat( "No", y_test.shape[0])
print(accuracy_score(y_test, y_pred_nv))

0.967


#### KFold CV

In [70]:
results = cross_val_score(pipe, X, y)
results.mean()

0.9731

### Wine Quality

In [77]:
wine = pd.read_csv("C:/Python/Datasets/wine.csv")
y = wine['Class']
X = wine.drop('Class', axis=1)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=24, test_size=0.3)
lr = LogisticRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print(accuracy_score(y_test, y_pred))

0.9074074074074074


C:\Python\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
